#+EXPORT_FILE_NAME: /home/epos/Blog/templates/a_better_download_button.html
#+HTML_HEAD: {{data['css']}}
#+HTML: {{data['header']}}

* Gload: A better download button
** Why?
During the summer I got re-absorbed (addicted) to Genshin Impact again, through some ADHD-train of thought I got to thinking about distributing a program written to /help/ someone play Genshin Impact more efficiently.

This was influenced by some posts on Reddit about how terrible it was for non-programmers to download software from and use GitHub in general, so I got to thinking about the alternatives which we already have.
** How would you do it in 2022?
*** So how would I publish a program I wrote for common usage?
Previously ([[https://github.com/epos95/byggis.git][hint, hint]]) I have used ~cargo~ and its excellent
#+begin_src bash
cargo install <package>
#+end_src
functionality.

This works great! Cargo makes it easy to install and distribute Rust applications, the problem comes from the fact that it requires ~cargo~ to be installed, something which non-programmers often do not.
*** So what are some of the better alternatives?
There are of course file hosting sites such as [[https://sourceforge.net/][sourceforge]], but considering how the number 2 google search containing sourceforge is "sourceforge safe" I would not count this as a good alternative. (WARNING: Strictly personal opinion to justify this entire program.)

You could also host pre-compiled executable files for each operating system inside your git repository (or on any other file hosting service availible to the user), this poses issues in that the user would most likely need to choose which executable to download.
This can't be assumed to be true for a given user so I would not count this as a good alternative either.

** Finally introducing Gload:
Gload is the service I wrote in Rust to try and remedy the earlier mentioned problems! It is build around the scenario of some developer having some code they want to share effortlessly. It assumes that the dev has access to some sort of simple hosting for the Gload service but nothing else.

Gload grabs the users' CPU architecture to compute the target triple [link to rust docs here] for that computer and then uses Cross [link here] to compile for that specific architecture and then returns the program to the user, all with minimal input from the user!

* Writing Gload
** The requirements for the program
- Be easy to use for anyone. Anyone should be able to use the service.
- Be aware of different user architectures. The service should make sure that the user gets the correct executable for the machine they are connecting from.
- Offload all the compilation from the user. The user should not have to install a compiler or toolchain to run or get the program on their computer.

** The technology used in the program
Since the specifications demanded minimal input from the user a webserver seemed like a great choice for hosting this service. The webserver space in Rust is very interesting with two of the most famous Rust webserver frameworks being in the top 10 fastest in the world according to [[https://www.techempower.com/benchmarks/#section=data-r21&test=composite][techempover.com]]. While speed was not critical for this service I had been seeing some talk about [[https://github.com/tokio-rs/axum][Axum]] on my Twitter timeline from the wonderful [[https://fasterthanli.me/https://fasterthanli.me/][fasterthanlime]] so I decided to try that.

Normally everything from the people at Tokio is /excellent/ and Axum is no exception, however I have always been a bit unfamiliar with the async ecosystem in Rust so this was a space I was happy to dive into more.

** Program architecture

* Deeper implementation details

* Personal take-aways from the project
